### ISSUE TITLE
We dont need counterparty to close channel as it can be obtained from signature

### ISSUE THREAD

**Issue by SCBuergel** [validitylabs/messagingProtocol#22]
https://github.com/validitylabs/messagingProtocol/blob/7b8d4afdbd9fe488ce5062a89c9a3e81df92767e/contracts/HoprChannel.sol#L182

**Comment by mswezey23** [comment]
As implemented `counterParty` is required as we need the `channelId` as seen below:
`bytes32 channelId = getId(counterParty);`

Which is part of the following code to verify the `counterParty`
```
bytes32 hashedMessage = keccak256(abi.encodePacked(balanceA, index, channelId));
require(ecrecover(hashedMessage, uint8(v) + 27, r, s) == counterParty, "Invalid signature.");
```

To remove `counterParty` from an input parameter we would then have to pass in the channelId. Is that was is desired?

**Comment by robertkiel** [comment]
See issue #29 why we definitively need channelID and/or counterparty
