### ISSUE TITLE
reopening existing payment channels

### ISSUE THREAD

**Issue by robertkiel** [validitylabs/messagingProtocol#29]
Assume that Alice and Bob had a payment channel with each other.

At some point in time, Alice closed the payment channel.

Now, Alice and Bob agreed to reopen the payment channel. Alice/Bob can now reuse the previously signed messages.

**Solution** make the channelID dependant of some other randomly chosen value.

**Comment by SCBuergel** [comment]
@robertkiel maybe we can keep incrementing the index when recycling the channel instead of resetting it to zero (otherwise update txs can be replayed!) and use the index at the time of (re-)opening the channel instead of a randomly chosen value?
